# Based off https://raw.githubusercontent.com/nextstrain/ncov/master/defaults/parameters.yaml as of early September 2020
# This file contains the subset of settings used in Nybbler
# These are the two main starting files for the run, for SARS-CoV-2 typically downloaded as nextmeta and next fasta from GISAID.
sequences: "data/sequences.fasta"
metadata: "data/metadata.tsv"

# Nybbler-specific settings for overriding sequences. These sequences are guaranteed to be representatives in the Nybbler output regardless of
# whether there are earlier samples with equivalent sequence in the regular  "sequeces" file.
# overriding_sequences: "data/local_sequences.fasta"
# overriding_metadata: "data/local_metadata.tsv"

# Define files used for external configuration. Common examples consist of a
# list of strains to include and exclude from analyses.
files:
  include: "defaults/include.txt"
  exclude: "defaults/exclude.txt"

# Filter settings
filter:
  # Require nearly full-length genomes.
  min_length: 27000

# Mask settings determine how the multiple sequence alignment is masked prior to phylogenetic inference.
mask:
  # Number of bases to mask from the beginning and end of the alignment. These regions of the genome
  # are difficult to sequence accurately.
  mask_from_beginning: 100
  mask_from_end: 50

  # Specific sites to mask in the reference genome's coordinates.
  # These are 1-indexed coordinates of sites that have been identified as prone to sequencing errors.
  # 13402, 24389 and 24390 are restricted to Belgian samples
  mask_sites: "13402 24389 24390"
  # URI VCF files of sites to mask, this is a parameter unique to Nybbler. 
  # The reference ID in the VCF must be retrievable from Genbank Nucleotide DB using NCBI Entrez e-utils.
  mask_sites_vcf: "https://github.com/W-L/ProblematicSites_SARS-CoV2/raw/master/subset_vcf/problematic_sites_sarsCov2.mask.vcf https://github.com/W-L/ProblematicSites_SARS-CoV2/raw/master/subset_vcf/problematic_sites_sarsCov2.caution.vcf"

# The following is only requored to define the reference strain in the "sequences" file, if mask_sites_vcf above was not provided.
refine:
  root: "Wuhan/Hu-1/2019 Wuhan/WH01/2019" 

