# Based off https://raw.githubusercontent.com/nextstrain/ncov/master/defaults/parameters.yaml as of early September 2020
# This file contains the subset of settings used in Nybbler
# These are the two main starting files for the run, for SARS-CoV-2 typically downloaded as nextmeta and nextfasta from GISAID.
sequences: "data/sequences.fasta"
metadata: "data/metadata.tsv"

# Nybbler-specific settings for overriding sequences. These sequences are guaranteed to be representatives in the Nybbler output regardless of
# whether there are earlier samples with equivalent sequence in the regular "sequences" file.
# overriding_sequences: "data/local_sequences.fasta"
# overriding_metadata: "data/local_metadata.tsv"

# Define files used for external configuration. Common examples consist of a
# list of strains to include and exclude from analyses.
files:
  include: "defaults/include.txt"
  exclude: "defaults/exclude.txt"

# Filter settings
filter:
  # Require nearly full-length genomes.
  min_length: 27000

# Mask settings determine how the multiple sequence alignment is masked prior to phylogenetic inference.
mask:
  # Number of bases to mask from the beginning and end of the alignment. These regions of the genome
  # are difficult to sequence accurately.
  mask_from_beginning: 100
  mask_from_end: 50

  # Specific sites to mask in the reference genome's coordinates.
  # These are 1-indexed coordinates of sites that have been identified as prone to sequencing errors.
  # 13402, 24389 and 24390 are restricted to Belgian samples (comment as per NextStrain YAML file)
  # Paul Gordon: A low frequency homoplasy encoding Spike protein H49Y (C21707T) is documented in https://jvi.asm.org/content/94/18/e01056-20
  # Checked NextStrain global analysis on 2020-10-16, the last occurrence of C21707T is late July, first in early February.
  mask_sites: "13402 21707 24389 24390"
  # URI VCF files of sites to mask, this is a parameter unique to Nybbler. 
  # The reference ID in the VCF must be retrievable from Genbank Nucleotide DB using NCBI Entrez e-utils.
  mask_sites_vcf: "https://github.com/W-L/ProblematicSites_SARS-CoV2/raw/master/subset_vcf/problematic_sites_sarsCov2.mask.vcf"

# The following is only required to define the reference strain in the "sequences" file, if mask_sites_vcf above was not provided.
refine:
  root: "Wuhan/Hu-1/2019 Wuhan/WH01/2019" 


# We are using a different subsampling strategy from NextStrain, where we are weighting the sampling on the estimated number of cases per country.
# So we are using the same param naming scheme but not the same params.
subsampling:
  # Default subsampling logic for regions
  region:
    # Focal samples for region
    region:
      group_by: "division year month"
      seq_per_group: 48
      exclude: "--exclude-where 'region!={region}'"
    # Contextual samples for region from the rest of the world
    global:
      group_by: "country year month"
      seq_per_group: 4
      exclude: "--exclude-where 'region={region}'"
      priorities:
        type: "proximity"
        focus: "region"

  # Custom subsampling logic for global region.
  region_global:
    global:
      group_by: "country year month"
      seq_per_group: 20

  # Custom subsampling logic for regions like Europe where grouping by country
  # is the smallest resolution required.
  region_grouped_by_country:
    # Focal samples for region
    region:
      group_by: "country year month"
      seq_per_group: 64
      exclude: "--exclude-where 'region!={region}'"
    # Contextual samples for region from the rest of the world
    global:
      group_by: "country year month"
      seq_per_group: 6
      exclude: "--exclude-where 'region={region}'"
      priorities:
        type: "proximity"
        focus: "region"

  # Default subsampling logic for countries
  country:
    # Focal samples for country
    country:
      # Added for Nybbler specifically, we have estimates of disease prevalence we want to use to guide sampling
      # Uncomment this line to generate a less-biased sampling strategy for MCMC input etc.
      # weighted_sampling_estimates: "country_ideal_sequences.csv"
      group_by: "division year month"
      seq_per_group: 200
      exclude: "--exclude-where 'country!={country}'"
    # Contextual samples from country's region
    region:
      group_by: "country year month"
      seq_per_group: 20
      exclude: "--exclude-where 'country={country}' 'region!={region}'"
      priorities:
        type: "proximity"
        focus: "country"
    # Contextual samples from the rest of the world,
    # excluding the current region to avoid resampling.
    global:
      group_by: "country year month"
      seq_per_group: 10
      exclude: "--exclude-where 'region={region}'"
      priorities:
        type: "proximity"
        focus: "country"
